sudo: required
before_script:
#- wget https://raw.githubusercontent.com/ckan/ckan/ckan-2.7.4/ckan/config/solr/schema.xml
#- curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | DEBUG=true SOLR_CORE=ckan SOLR_VERSION=4.7.2 SOLR_CONFS="schema.xml" SOLR_DOCS=custom_docs.json bash
- echo "Installing solr 4.7.2"
- cd /opt
- sudo wget http://archive.apache.org/dist/lucene/solr/4.7.2/solr-4.7.2.tgz
- sudo tar -xvf solr-4.7.2.tgz
- sudo cp -R solr-4.7.2/example /opt/solr
- sudo mv /opt/solr/solr/collection1 /opt/solr/solr/ckan
- echo "name=ckan" | sudo tee /opt/solr/solr/ckan/core.properties
- sudo wget https://raw.githubusercontent.com/ckan/ckan/ckan-2.7.4/ckan/config/solr/schema.xml -O /opt/solr/solr/ckan/conf/schema.xml
- sudo wget https://raw.githubusercontent.com/datosgobar/portal-base/master/solr/jetty-logging.xml -O /opt/solr/etc/jetty-logging.xml
- echo "NO_START=0\nJETTY_HOST=127.0.0.1\nJETTY_PORT=8983\nJAVA_HOME=$JAVA_HOME" | sudo tee /etc/default/jetty
#- sudo java -jar /opt/solr/start.jar --daemon
- sudo java -Djetty.port=$JETTY_PORT -jar start.jar &
- cd -

script:
- curl http://localhost:8983/solr/ckan/
